// src/lib/components/layout/Navbar.svelte
<script lang="ts">
	import { base } from '$app/paths';
	import { cn } from '$lib/utils/cn.js';
	import { navLinks } from '$lib/data/mock.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Menu, X, ShoppingBag, Search } from 'lucide-svelte';

	let { class: className }: { class?: string } = $props();

	let mobileOpen = $state(false);
	let scrolled = $state(false);

	function handleScroll() {
		scrolled = window.scrollY > 20;
	}
</script>

<svelte:window onscroll={handleScroll} />

<header
	class={cn(
		'fixed top-0 left-0 right-0 z-50 transition-all duration-300',
		scrolled
			? 'bg-surface/95 backdrop-blur-md shadow-sm border-b border-border'
			: 'bg-transparent',
		className
	)}
>
	<nav class="mx-auto flex h-16 max-w-[1280px] items-center justify-between px-4 sm:px-6 lg:px-8">
		<!-- Logo -->
		<a href="{base}/" class="flex items-center gap-2">
			<img
				src="https://www.beingmuslim.org/wp-content/uploads/2022/01/tree-logo-inverse.png"
				alt="Being Muslim"
				class="h-8 w-8 {scrolled ? 'invert' : ''}"
				style="transition: filter 0.3s;"
			/>
			<span class={cn(
				'font-display text-lg font-bold transition-colors',
				scrolled ? 'text-text-primary' : 'text-text-cream'
			)}>Being Muslim</span>
		</a>

		<!-- Desktop Nav -->
		<div class="hidden items-center gap-1 md:flex">
			{#each navLinks as link}
				<a
					href={link.href}
					class={cn(
						'rounded-lg px-3 py-2 text-sm font-medium transition-colors hover:bg-white/10',
						scrolled
							? 'text-text-primary hover:bg-secondary'
							: 'text-text-cream/90 hover:text-text-cream'
					)}
				>
					{link.label}
				</a>
			{/each}
		</div>

		<!-- Desktop Actions -->
		<div class="hidden items-center gap-2 md:flex">
			<button
				class={cn(
					'rounded-lg p-2 transition-colors',
					scrolled
						? 'text-text-secondary hover:text-text-primary hover:bg-secondary'
						: 'text-text-cream/80 hover:text-text-cream hover:bg-white/10'
				)}
				aria-label="Search"
			>
				<Search class="h-5 w-5" />
			</button>
			<button
				class={cn(
					'relative rounded-lg p-2 transition-colors',
					scrolled
						? 'text-text-secondary hover:text-text-primary hover:bg-secondary'
						: 'text-text-cream/80 hover:text-text-cream hover:bg-white/10'
				)}
				aria-label="Cart"
			>
				<ShoppingBag class="h-5 w-5" />
				<span class="absolute -top-0.5 -right-0.5 flex h-4 w-4 items-center justify-center rounded-full bg-accent-primary text-[10px] font-bold text-text-cream">
					2
				</span>
			</button>
			<Button variant="default" size="sm" class="ml-2">
				{#snippet children()}
					Sign In
				{/snippet}
			</Button>
		</div>

		<!-- Mobile Menu Button -->
		<button
			class={cn(
				'rounded-lg p-2 md:hidden',
				scrolled
					? 'text-text-primary hover:bg-secondary'
					: 'text-text-cream hover:bg-white/10'
			)}
			onclick={() => (mobileOpen = !mobileOpen)}
			aria-label="Toggle menu"
		>
			{#if mobileOpen}
				<X class="h-6 w-6" />
			{:else}
				<Menu class="h-6 w-6" />
			{/if}
		</button>
	</nav>

	<!-- Mobile Menu -->
	{#if mobileOpen}
		<div class="border-t border-border bg-surface p-4 shadow-lg md:hidden">
			<div class="flex flex-col gap-1">
				{#each navLinks as link}
					<a
						href={link.href}
						class="rounded-lg px-3 py-2.5 text-sm font-medium text-text-primary hover:bg-secondary"
						onclick={() => (mobileOpen = false)}
					>
						{link.label}
					</a>
				{/each}
				<hr class="my-2 border-border" />
				<div class="flex gap-2">
					<Button variant="outline" size="sm" class="flex-1">
						{#snippet children()}
							<Search class="mr-1 h-4 w-4" />
							Search
						{/snippet}
					</Button>
					<Button variant="outline" size="sm" class="flex-1">
						{#snippet children()}
							<ShoppingBag class="mr-1 h-4 w-4" />
							Cart (2)
						{/snippet}
					</Button>
				</div>
				<Button variant="default" size="default" class="mt-2 w-full">
					{#snippet children()}
						Sign In
					{/snippet}
				</Button>
			</div>
		</div>
	{/if}
</header>

// src/app/f/Navbar.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import type { ComponentType } from "react";
import Link from "next/link";
import {
  Menu,
  X,
  BookOpen,
  GraduationCap,
  BookMarked,
  Compass,
  Users,
  HelpCircle,
  ShoppingBag,
  Package,
  Layers,
  Tablet,
  Heart,
  Gift,
  HandHeart,
} from "lucide-react";
import { css } from "@/lib/css";

type LucideIcon = ComponentType<{ size?: number; strokeWidth?: number; color?: string }>;
type MenuRow = {
  icon: LucideIcon;
  title: string;
  desc: string;
  href: string;
  /** Accent color for the icon + title. Defaults to teal. */
  accent?: "teal" | "gold";
};

const TEAL = "#1f8a70";
const GOLD = "#f5c518";
// The title color leans into a slightly deeper teal for legibility.
const TITLE_TEAL = "#15302e";

const megaMenus: Record<string, MenuRow[]> = {
  Learn: [
    { icon: BookOpen, title: "Articles", desc: "In-depth guides on faith and practice", href: "/f/learn", accent: "teal" },
    { icon: GraduationCap, title: "Get Started", desc: "First steps for new Muslims", href: "/f/learn/beginners-guide", accent: "gold" },
    { icon: BookMarked, title: "Overview of Islam", desc: "Core beliefs, practices, and history", href: "/f/learn/brief-overview-of-islam", accent: "teal" },
  ],
  Convert: [
    { icon: Compass, title: "Ready to Convert?", desc: "Take the next step with guidance and support", href: "/f/convert", accent: "teal" },
    { icon: Users, title: "Find a Community", desc: "Connect with Muslims near you", href: "/f/convert", accent: "gold" },
    { icon: HelpCircle, title: "FAQ for Reverts", desc: "Answers to the most common questions", href: "/f/convert", accent: "teal" },
  ],
  Products: [
    { icon: BookOpen, title: "The Book", desc: "Being Muslim: A Practical Guide", href: "/f/shop/book", accent: "teal" },
    { icon: Package, title: "Boxed Set", desc: "Book, prayer cards, and more", href: "/f/shop/boxed-set", accent: "gold" },
    { icon: Layers, title: "Prayer Cards", desc: "Keep by your prayer mat", href: "/f/shop/prayer-cards", accent: "teal" },
    { icon: Tablet, title: "Digital Edition", desc: "Read anywhere, instantly", href: "/f/shop/ebook", accent: "gold" },
  ],
  Support: [
    { icon: Heart, title: "Donate", desc: "Help fund resources for new Muslims", href: "/f/support", accent: "teal" },
    { icon: Gift, title: "Sponsor a Set", desc: "Gift a boxed set to someone in need", href: "/f/support", accent: "gold" },
    { icon: HandHeart, title: "Volunteer", desc: "Join our team of contributors", href: "/f/support", accent: "teal" },
  ],
};

const navLinks: { label: string; href: string }[] = [
  { label: "Home", href: "/f" },
  { label: "Learn", href: "/f/learn" },
  { label: "Convert", href: "/f/convert" },
  { label: "Products", href: "/f/shop" },
  { label: "Support", href: "/f/support" },
];

export default function Navbar() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [activeMenu, setActiveMenu] = useState<string | null>(null);
  const closeTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  function openMenu(label: string) {
    if (closeTimeout.current) clearTimeout(closeTimeout.current);
    setActiveMenu(label);
  }
  function scheduleClose() {
    closeTimeout.current = setTimeout(() => setActiveMenu(null), 150);
  }
  function cancelClose() {
    if (closeTimeout.current) clearTimeout(closeTimeout.current);
  }

  const solid = scrolled || !!activeMenu || mobileOpen;

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 border-b transition-all duration-300 ${
        solid ? "backdrop-blur-md shadow-sm border-border" : "border-transparent"
      }`}
      style={
        solid
          ? css("background: rgba(249,247,242,0.97)")
          : css("background: rgba(249,247,242,0.7); backdrop-filter: blur(8px); -webkit-backdrop-filter: blur(8px)")
      }
    >
      <nav className="mx-auto flex h-[72px] max-w-[1240px] items-center justify-between px-6 lg:px-8">
        {/* Logo */}
        <Link href="/f" className="flex items-center gap-2.5">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="https://www.beingmuslim.org/wp-content/uploads/2022/01/tree-logo-inverse.png"
            alt="Being Muslim"
            className="h-8 w-8 invert"
            style={css("transition: filter 0.3s")}
          />
          <span className="text-lg font-bold transition-colors" style={css("font-family: 'Inter', sans-serif; color: #1d2b29")}>
            Being Muslim
          </span>
        </Link>

        {/* Desktop Nav */}
        <div className="hidden items-center gap-8 md:flex">
          {navLinks.map((link) => {
            const rows = megaMenus[link.label];
            const open = activeMenu === link.label;
            return (
              <div
                key={link.label}
                className="relative"
                onMouseEnter={() => (rows ? openMenu(link.label) : setActiveMenu(null))}
                onMouseLeave={scheduleClose}
              >
                <Link
                  href={link.href}
                  className="bm-link-animated text-[15px] font-medium transition-colors py-6 inline-block"
                  style={css("font-family: 'Inter', sans-serif; color: #1d2b29")}
                >
                  {link.label}
                </Link>

                {/* Beginnings-style dropdown card */}
                {rows && open && (
                  <div
                    className="bm-dropdown"
                    onMouseEnter={cancelClose}
                    onMouseLeave={scheduleClose}
                  >
                    <div className="bm-dropdown-caret" />
                    <div className="bm-dropdown-card">
                      {rows.map((row) => {
                        const Icon = row.icon;
                        const accent = row.accent === "gold" ? GOLD : TEAL;
                        return (
                          <Link key={row.title} href={row.href} className="bm-dropdown-row">
                            <span
                              className="bm-dropdown-icon"
                              style={css(`color: ${accent}`)}
                            >
                              <Icon size={26} strokeWidth={1.75} />
                            </span>
                            <span style={css("display: flex; flex-direction: column; gap: 2px")}>
                              <span
                                className="bm-dropdown-title"
                                style={css(`color: ${row.accent === "gold" ? "#a87d00" : TITLE_TEAL}`)}
                              >
                                {row.title}
                              </span>
                              <span className="bm-dropdown-desc">{row.desc}</span>
                            </span>
                          </Link>
                        );
                      })}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Desktop CTA */}
        <Link
          href="/f/support"
          className="hidden md:inline-flex items-center gap-1.5 px-6 py-2.5 rounded-full text-[15px] font-semibold transition-all bm-btn-gold"
          style={css("font-family: 'Inter', sans-serif")}
        >
          Donate
        </Link>

        {/* Mobile Menu Button */}
        <button
          className="rounded-lg p-2 md:hidden"
          style={css("color: #1d2b29")}
          onClick={() => setMobileOpen((v) => !v)}
          aria-label="Toggle menu"
        >
          {mobileOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
        </button>
      </nav>

      {/* Mobile menu */}
      <div className={`mobile-menu md:hidden ${mobileOpen ? "open" : ""}`}>
        <div className="px-6 py-4" style={css("border-top: 1px solid #ece7dd")}>
          {navLinks.map((link) => (
            <Link key={link.label} href={link.href} className="block py-2.5 font-medium" style={css("font-family: 'Inter', sans-serif; color: #1d2b29")} onClick={() => setMobileOpen(false)}>
              {link.label}
            </Link>
          ))}
          <Link href="/f/support" className="block mt-3 text-center py-2.5 rounded-full font-semibold bm-btn-gold" style={css("justify-content: center; font-family: 'Inter', sans-serif")} onClick={() => setMobileOpen(false)}>
            Donate
          </Link>
        </div>
      </div>
    </header>
  );
}
