// src/app/a-staging/shop/book/page.tsx
import Link from "next/link";
import { ArrowLeft, ShoppingCart, Globe } from "lucide-react";
import { css } from "@/lib/css";

const languageThumbs = [
  { label: "English", href: "/a-staging/shop/book", active: true },
  { label: "Español", href: "/a-staging/shop/book/spanish", active: false },
  { label: "Português", href: "/a-staging/shop/book/portuguese", active: false },
];

export const metadata = {
  title: "Being Muslim: A Practical Guide — Being Muslim Shop",
  description:
    "The essential guide for new Muslims by Dr. Asad Tarsin. Clear, warm, and comprehensive — covering beliefs, prayer, fasting, and daily Muslim life.",
};

const related = [
  { title: "The Complete Boxed Set", price: "$85.00", img: "https://www.beingmuslim.org/wp-content/uploads/2021/08/the-boxed-set-900x1200.jpeg", href: "/a-staging/shop/boxed-set" },
  { title: "Prayer Reference Cards", price: "$37.50", img: "https://www.beingmuslim.org/wp-content/uploads/2021/08/the-prayer-card-900x610.jpeg", href: "/a-staging/shop/prayer-cards" },
  { title: "Digital Edition (eBook)", price: "$9.00", img: "https://www.beingmuslim.org/wp-content/uploads/2021/08/BM-E-Book-900x1200.png", href: "/a-staging/shop/ebook" },
];

export default function ConceptAStagingShopBook() {
  return (
    <>
      {/* Breadcrumb */}
      <section style={css("background: #e9e3da; padding-top: 72px")}>
        <div className="mx-auto max-w-[1400px] px-6 lg:px-10 py-4">
          <Link
            href="/a-staging/shop"
            style={css("color: #8a7e70; font-family: 'DM Sans', sans-serif")}
            className="inline-flex items-center gap-2 text-sm transition-colors hover:text-[#2a2018]"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Products
          </Link>
        </div>
      </section>

      {/* Product Detail */}
      <section style={css("background: #f0ebe3")}>
        <div className="mx-auto max-w-[1400px] px-6 lg:px-10 py-12">
          {/* Language switcher (translated editions) */}
          <div style={css("display: flex; flex-wrap: wrap; align-items: center; gap: 10px; margin-bottom: 28px")}>
            <span className="inline-flex items-center gap-1.5" style={css("font-family: 'DM Sans', sans-serif; font-size: 12px; font-weight: 600; color: #8a7e70; text-transform: uppercase; letter-spacing: 0.06em")}>
              <Globe className="h-3.5 w-3.5" />
              Languages
            </span>
            {languageThumbs.map((lang) => (
              <Link
                key={lang.label}
                href={lang.href}
                style={css(`font-family: 'DM Sans', sans-serif; font-size: 13px; font-weight: 500; text-decoration: none; border-radius: 999px; padding: 6px 14px; border: 1px solid ${lang.active ? "#2a2018" : "#d4cec4"}; color: ${lang.active ? "#faf2e3" : "#2a2018"}; background: ${lang.active ? "#2a2018" : "transparent"}`)}
              >
                {lang.label}
              </Link>
            ))}
            <Link
              href="/a-staging/shop/languages"
              className="inline-flex items-center gap-1"
              style={css("font-family: 'DM Sans', sans-serif; font-size: 13px; font-weight: 500; color: #8b2e36; text-decoration: none; margin-left: 4px")}
            >
              View all languages
            </Link>
          </div>

          <div className="bm-grid-detail">
            {/* Image */}
            <div style={css("background: #e2dcd2; border-radius: 16px; overflow: hidden; aspect-ratio: 3/4")}>
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src="https://www.beingmuslim.org/wp-content/uploads/2021/08/being-muslim-book.jpeg"
                alt="Being Muslim: A Practical Guide"
                style={css("width: 100%; height: 100%; object-fit: cover; display: block")}
              />
            </div>

            {/* Details */}
            <div style={css("font-family: 'DM Sans', sans-serif")}>
              <span
                style={css("background: rgba(196,169,125,0.2); color: #c4a97d")}
                className="inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold mb-4"
              >
                Bestseller
              </span>

              <h1 style={css("font-family: 'Source Serif 4', serif; font-size: 36px; font-weight: 400; color: #2a2018; margin: 0 0 12px; line-height: 1.15")}>
                Being Muslim: A Practical Guide
              </h1>

              <p style={css("font-size: 14px; color: #8a7e70; margin: 0 0 16px")}>By Dr. Asad Tarsin</p>

              <p style={css("font-family: 'Source Serif 4', serif; font-size: 32px; font-weight: 400; color: #2a2018; margin: 0 0 24px")}>
                $14.95
              </p>

              <p style={css("font-size: 15px; color: #5a5248; line-height: 1.7; margin: 0 0 24px")}>
                The essential guide for new Muslims and anyone seeking a clear, warm, and comprehensive introduction to Islam. Written by acclaimed Islamic educator Dr. Asad Tarsin, this beautifully designed book covers the core beliefs and practices of Islam — from the five pillars and daily prayer to fasting, charity, and building a meaningful relationship with God. Whether you are a new convert, someone returning to the faith, or simply curious, this book meets you where you are.
              </p>

              <ul style={css("font-size: 14px; color: #5a5248; line-height: 2; margin: 0 0 32px; padding-left: 20px")}>
                <li>Full-color illustrations throughout</li>
                <li>Step-by-step prayer guide</li>
                <li>Covers the five pillars in depth</li>
                <li>Written for new Muslims and reconnectors</li>
                <li>Available in multiple languages</li>
              </ul>

              <div style={css("display: flex; gap: 12px; margin-bottom: 24px")}>
                <button className="bm-btn-dark" style={css("padding: 14px 32px; font-size: 15px")}>
                  <ShoppingCart className="h-4 w-4" />
                  Add to Cart
                </button>
                <button className="bm-btn-outline" style={css("padding: 14px 32px; font-size: 15px")}>
                  Buy Now
                </button>
              </div>

              <div style={css("border-top: 1px solid #d8d2c8; padding-top: 20px; display: flex; gap: 24px; font-size: 13px; color: #8a7e70")}>
                <span>Free shipping over $50</span>
                <span>30-day returns</span>
                <span>Secure checkout</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Related Products */}
      <section style={css("background: #fff")} className="bm-section-padding">
        <div className="mx-auto max-w-[1400px] px-6 lg:px-10">
          <h2 style={css("font-family: 'Source Serif 4', serif; font-size: 28px; font-weight: 400; color: #2a2018; margin: 0 0 24px")}>
            You might also like
          </h2>
          <div className="bm-grid-3">
            {related.map((product) => (
              <Link
                key={product.title}
                href={product.href}
                style={css("text-decoration: none")}
                className="bm-title-underline-parent group"
              >
                <div style={css("aspect-ratio: 1; background: #e2dcd2; border-radius: 12px; overflow: hidden; margin-bottom: 12px")}>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={product.img}
                    alt={product.title}
                    className="transition-transform duration-500 group-hover:scale-105"
                    style={css("width: 100%; height: 100%; object-fit: cover; display: block")}
                  />
                </div>
                <h3 className="bm-title-underline" style={css("font-family: 'Source Serif 4', serif; font-size: 16px; font-weight: 400; color: #2a2018; margin: 0 0 4px")}>
                  {product.title}
                </h3>
                <span style={css("font-family: 'DM Sans', sans-serif; font-size: 14px; font-weight: 500; color: #2a2018")}>
                  {product.price}
                </span>
              </Link>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}

// src/routes/b/(public)/shop/book/+page.svelte
<script lang="ts">
	import { ArrowLeft, ArrowRight, ShoppingCart } from 'lucide-svelte';
</script>

<svelte:head>
	<title>Being Muslim: A Practical Guide — Being Muslim Shop</title>
	<meta
		name="description"
		content="The essential guide for new Muslims by Dr. Asad Tarsin. Clear, warm, and comprehensive — covering beliefs, prayer, fasting, and daily Muslim life."
	/>
</svelte:head>

<!-- Breadcrumb -->
<section style="background: #e9e3da; padding-top: 72px;">
	<div class="mx-auto max-w-[1400px] px-6 lg:px-10 py-4">
		<a
			href="/b/shop"
			style="color: #8a7e70; font-family: 'DM Sans', sans-serif;"
			class="inline-flex items-center gap-2 text-sm transition-colors hover:text-[#2a2018]"
		>
			<ArrowLeft class="h-4 w-4" />
			Back to Shop
		</a>
	</div>
</section>

<!-- Product Detail -->
<section style="background: #f0ebe3;">
	<div class="mx-auto max-w-[1400px] px-6 lg:px-10 py-12">
		<div class="bm-grid-detail">
			<!-- Image -->
			<div style="background: #e2dcd2; border-radius: 16px; overflow: hidden; aspect-ratio: 3/4;">
				<img
					src="https://www.beingmuslim.org/wp-content/uploads/2021/08/being-muslim-book.jpeg"
					alt="Being Muslim: A Practical Guide"
					style="width: 100%; height: 100%; object-fit: cover; display: block;"
				/>
			</div>

			<!-- Details -->
			<div style="font-family: 'DM Sans', sans-serif;">
				<span
					style="background: rgba(196,169,125,0.2); color: #c4a97d;"
					class="inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold mb-4"
				>
					Bestseller
				</span>

				<h1 style="font-family: 'Source Serif 4', serif; font-size: 36px; font-weight: 400; color: #2a2018; margin: 0 0 12px; line-height: 1.15;">
					Being Muslim: A Practical Guide
				</h1>

				<p style="font-size: 14px; color: #8a7e70; margin: 0 0 16px;">By Dr. Asad Tarsin</p>

				<p style="font-family: 'Source Serif 4', serif; font-size: 32px; font-weight: 400; color: #2a2018; margin: 0 0 24px;">
					$14.95
				</p>

				<p style="font-size: 15px; color: #5a5248; line-height: 1.7; margin: 0 0 24px;">
					The essential guide for new Muslims and anyone seeking a clear, warm, and comprehensive introduction to Islam. Written by acclaimed Islamic educator Dr. Asad Tarsin, this beautifully designed book covers the core beliefs and practices of Islam — from the five pillars and daily prayer to fasting, charity, and building a meaningful relationship with God. Whether you are a new convert, someone returning to the faith, or simply curious, this book meets you where you are.
				</p>

				<ul style="font-size: 14px; color: #5a5248; line-height: 2; margin: 0 0 32px; padding-left: 20px;">
					<li>Full-color illustrations throughout</li>
					<li>Step-by-step prayer guide</li>
					<li>Covers the five pillars in depth</li>
					<li>Written for new Muslims and reconnectors</li>
					<li>Available in multiple languages</li>
				</ul>

				<div style="display: flex; gap: 12px; margin-bottom: 24px;">
					<button class="bm-btn-dark" style="padding: 14px 32px; font-size: 15px;">
						<ShoppingCart class="h-4 w-4" />
						Add to Cart
					</button>
					<button class="bm-btn-outline" style="padding: 14px 32px; font-size: 15px;">
						Buy Now
					</button>
				</div>

				<div style="border-top: 1px solid #d8d2c8; padding-top: 20px; display: flex; gap: 24px; font-size: 13px; color: #8a7e70;">
					<span>Free shipping over $50</span>
					<span>30-day returns</span>
					<span>Secure checkout</span>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- Related Products -->
<section style="background: #fff;" class="bm-section-padding">
	<div class="mx-auto max-w-[1400px] px-6 lg:px-10">
		<h2 style="font-family: 'Source Serif 4', serif; font-size: 28px; font-weight: 400; color: #2a2018; margin: 0 0 24px;">
			You might also like
		</h2>
		<div class="bm-grid-3">
			{#each [
				{ title: 'The Complete Boxed Set', price: '$85.00', img: 'https://www.beingmuslim.org/wp-content/uploads/2021/08/the-boxed-set-900x1200.jpeg', href: '/b/shop/boxed-set' },
				{ title: 'Prayer Reference Cards', price: '$37.50', img: 'https://www.beingmuslim.org/wp-content/uploads/2021/08/the-prayer-card-900x610.jpeg', href: '/b/shop/prayer-cards' },
				{ title: 'Digital Edition (eBook)', price: '$9.00', img: 'https://www.beingmuslim.org/wp-content/uploads/2021/08/BM-E-Book-900x1200.png', href: '/b/shop/ebook' }
			] as product}
				<a href={product.href} style="text-decoration: none;" class="bm-title-underline-parent group">
					<div style="aspect-ratio: 1; background: #e2dcd2; border-radius: 12px; overflow: hidden; margin-bottom: 12px;">
						<img src={product.img} alt={product.title} class="transition-transform duration-500 group-hover:scale-105" style="width: 100%; height: 100%; object-fit: cover; display: block;" />
					</div>
					<h3 class="bm-title-underline" style="font-family: 'Source Serif 4', serif; font-size: 16px; font-weight: 400; color: #2a2018; margin: 0 0 4px;">{product.title}</h3>
					<span style="font-family: 'DM Sans', sans-serif; font-size: 14px; font-weight: 500; color: #2a2018;">{product.price}</span>
				</a>
			{/each}
		</div>
	</div>
</section>
