// src/app/b-staging/Navbar.tsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Menu, X } from "lucide-react";
import { css } from "@/lib/css";

const navLinks = [
  { label: "Home", href: "/b-staging" },
  { label: "Learn", href: "/b-staging/learn" },
  { label: "Convert", href: "/b-staging/convert" },
  { label: "Shop", href: "/b-staging/shop" },
  { label: "Support", href: "/b-staging/support" },
];

export default function Navbar() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <header className="fixed top-0 left-0 right-0 z-50" style={css("padding: 16px 24px")}>
      {/* Desktop: pill navbar (always visible on md+) */}
      <nav
        className="bm-navbar-pill hidden md:flex"
        style={css(
          "max-width: 1100px; margin: 0 auto; align-items: center; justify-content: space-between; padding: 10px 12px 10px 20px; border-radius: 999px; backdrop-filter: blur(20px); -webkit-backdrop-filter: blur(20px); border: 1px solid rgba(255,255,255,0.15); background: rgba(255,255,255,0.08); box-shadow: none; transition: all 0.3s",
        )}
      >
        <Link href="/b-staging" style={css("display: flex; align-items: center; gap: 10px; text-decoration: none")}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="https://www.beingmuslim.org/wp-content/uploads/2022/01/tree-logo-inverse.png" alt="Being Muslim" style={css("height: 28px; width: 28px")} />
          <span style={css("font-family: 'DM Sans', sans-serif; font-size: 16px; font-weight: 700; color: #fff")}>Being Muslim</span>
        </Link>
        <div style={css("display: flex; align-items: center; gap: 28px")}>
          {navLinks.map((link) => (
            <Link
              key={link.label}
              href={link.href}
              style={css("font-family: 'DM Sans', sans-serif; font-size: 13px; font-weight: 500; text-decoration: none; color: rgba(255,255,255,0.85); padding: 6px 14px; border-radius: 999px")}
            >
              {link.label}
            </Link>
          ))}
        </div>
        <Link
          href="/b-staging/contact"
          style={css("align-items: center; padding: 8px 20px; border-radius: 999px; font-family: 'DM Sans', sans-serif; font-size: 13px; font-weight: 500; text-decoration: none; transition: all 0.3s; background: rgba(255,255,255,0.15); color: #fff; border: 1px solid rgba(255,255,255,0.25)")}
        >
          Contact
        </Link>
      </nav>

      {/* Mobile: single glass container that expands */}
      <div className={`mobile-shell md:hidden ${mobileOpen ? "open" : ""}`}>
        {/* Top row: logo + hamburger */}
        <div style={css("display: flex; align-items: center; justify-content: space-between; padding: 10px 12px 10px 20px")}>
          <Link href="/b-staging" style={css("display: flex; align-items: center; gap: 10px; text-decoration: none")}>
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src="https://www.beingmuslim.org/wp-content/uploads/2022/01/tree-logo-inverse.png" alt="Being Muslim" style={css("height: 28px; width: 28px")} />
            <span style={css("font-family: 'DM Sans', sans-serif; font-size: 16px; font-weight: 700; color: #fff")}>Being Muslim</span>
          </Link>
          <button
            style={css("padding: 8px; border: none; background: none; cursor: pointer; color: #fff")}
            onClick={() => setMobileOpen((v) => !v)}
            aria-label="Toggle menu"
          >
            {mobileOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
          </button>
        </div>

        {/* Expandable links */}
        <div className="mobile-links">
          <div style={css("padding: 4px 20px 16px")}>
            {navLinks.map((link) => (
              <Link
                key={link.label}
                href={link.href}
                style={css("display: block; padding: 10px 0; font-family: 'DM Sans', sans-serif; font-size: 14px; font-weight: 500; color: #fff; text-decoration: none")}
                onClick={() => setMobileOpen(false)}
              >
                {link.label}
              </Link>
            ))}
            <Link
              href="/b-staging/contact"
              style={css("display: block; margin-top: 8px; text-align: center; background: rgba(255,255,255,0.15); color: #fff; padding: 10px; border-radius: 999px; font-family: 'DM Sans', sans-serif; font-size: 14px; font-weight: 500; text-decoration: none; border: 1px solid rgba(255,255,255,0.25)")}
              onClick={() => setMobileOpen(false)}
            >
              Contact
            </Link>
          </div>
        </div>
      </div>
    </header>
  );
}

// src/lib/components/layout/Navbar.svelte
<script lang="ts">
	import { base } from '$app/paths';
	import { cn } from '$lib/utils/cn.js';
	import { navLinks } from '$lib/data/mock.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Menu, X, ShoppingBag, Search } from 'lucide-svelte';

	let { class: className }: { class?: string } = $props();

	let mobileOpen = $state(false);
	let scrolled = $state(false);

	function handleScroll() {
		scrolled = window.scrollY > 20;
	}
</script>

<svelte:window onscroll={handleScroll} />

<header
	class={cn(
		'fixed top-0 left-0 right-0 z-50 transition-all duration-300',
		scrolled
			? 'bg-surface/95 backdrop-blur-md shadow-sm border-b border-border'
			: 'bg-transparent',
		className
	)}
>
	<nav class="mx-auto flex h-16 max-w-[1280px] items-center justify-between px-4 sm:px-6 lg:px-8">
		<!-- Logo -->
		<a href="{base}/" class="flex items-center gap-2">
			<img
				src="https://www.beingmuslim.org/wp-content/uploads/2022/01/tree-logo-inverse.png"
				alt="Being Muslim"
				class="h-8 w-8 {scrolled ? 'invert' : ''}"
				style="transition: filter 0.3s;"
			/>
			<span class={cn(
				'font-display text-lg font-bold transition-colors',
				scrolled ? 'text-text-primary' : 'text-text-cream'
			)}>Being Muslim</span>
		</a>

		<!-- Desktop Nav -->
		<div class="hidden items-center gap-1 md:flex">
			{#each navLinks as link}
				<a
					href={link.href}
					class={cn(
						'rounded-lg px-3 py-2 text-sm font-medium transition-colors hover:bg-white/10',
						scrolled
							? 'text-text-primary hover:bg-secondary'
							: 'text-text-cream/90 hover:text-text-cream'
					)}
				>
					{link.label}
				</a>
			{/each}
		</div>

		<!-- Desktop Actions -->
		<div class="hidden items-center gap-2 md:flex">
			<button
				class={cn(
					'rounded-lg p-2 transition-colors',
					scrolled
						? 'text-text-secondary hover:text-text-primary hover:bg-secondary'
						: 'text-text-cream/80 hover:text-text-cream hover:bg-white/10'
				)}
				aria-label="Search"
			>
				<Search class="h-5 w-5" />
			</button>
			<button
				class={cn(
					'relative rounded-lg p-2 transition-colors',
					scrolled
						? 'text-text-secondary hover:text-text-primary hover:bg-secondary'
						: 'text-text-cream/80 hover:text-text-cream hover:bg-white/10'
				)}
				aria-label="Cart"
			>
				<ShoppingBag class="h-5 w-5" />
				<span class="absolute -top-0.5 -right-0.5 flex h-4 w-4 items-center justify-center rounded-full bg-accent-primary text-[10px] font-bold text-text-cream">
					2
				</span>
			</button>
			<Button variant="default" size="sm" class="ml-2">
				{#snippet children()}
					Sign In
				{/snippet}
			</Button>
		</div>

		<!-- Mobile Menu Button -->
		<button
			class={cn(
				'rounded-lg p-2 md:hidden',
				scrolled
					? 'text-text-primary hover:bg-secondary'
					: 'text-text-cream hover:bg-white/10'
			)}
			onclick={() => (mobileOpen = !mobileOpen)}
			aria-label="Toggle menu"
		>
			{#if mobileOpen}
				<X class="h-6 w-6" />
			{:else}
				<Menu class="h-6 w-6" />
			{/if}
		</button>
	</nav>

	<!-- Mobile Menu -->
	{#if mobileOpen}
		<div class="border-t border-border bg-surface p-4 shadow-lg md:hidden">
			<div class="flex flex-col gap-1">
				{#each navLinks as link}
					<a
						href={link.href}
						class="rounded-lg px-3 py-2.5 text-sm font-medium text-text-primary hover:bg-secondary"
						onclick={() => (mobileOpen = false)}
					>
						{link.label}
					</a>
				{/each}
				<hr class="my-2 border-border" />
				<div class="flex gap-2">
					<Button variant="outline" size="sm" class="flex-1">
						{#snippet children()}
							<Search class="mr-1 h-4 w-4" />
							Search
						{/snippet}
					</Button>
					<Button variant="outline" size="sm" class="flex-1">
						{#snippet children()}
							<ShoppingBag class="mr-1 h-4 w-4" />
							Cart (2)
						{/snippet}
					</Button>
				</div>
				<Button variant="default" size="default" class="mt-2 w-full">
					{#snippet children()}
						Sign In
					{/snippet}
				</Button>
			</div>
		</div>
	{/if}
</header>
